version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - /root/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    links:
      - php
    networks:
      - app-network
      - nginx-proxy-manager_default
  php:
    build:
      context: .
      dockerfile: Dockerfile

networks:
  app-network:
    # driver: bridge
  nginx-proxy-manager_default:
    external: true