version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - ./vendor:/var/www/html/vendor
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - .:/var/www/html
      - ./vendor:/var/www/html/vendor
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 9000:80
    networks:
      - app-network
      - nginx-proxy-manager_default

networks:
  app-network:
    # driver: bridge
  nginx-proxy-manager_default:
    external: true